# theme: jekyll-theme-cayman
title: "KDone"
remote_theme: pmarsceill/just-the-docs

# Aux links for the upper right navigation
aux_links:
  "KDone on GitHub":
  - https://github.com/dariopellegrini/KDone

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false

gh_edit_link: false

footer_content: "Copyright &copy; 2021 Dario Pellegrini"
color_scheme: dark
